// src/game-engine/sim/parityScript.ts
// WP04 chunk W4b's ONE source of truth for a parity fixture's scripted
// line. Walks a headless CampaignRunner through Beats 1-5, a caller-supplied
// phase-A leg (reserveLine's own walkToFirstCrew, or investLine's extra
// walkToSecondCrew on top), the cycle-1 pending-settlement decision, a
// save/reload round trip (proving the headless reload seam — 07's own
// "save and reload at the specified checkpoint" — before continuing on the
// SAME live rc, exactly runner.determinism.test.ts's own reload-continuation
// shape), then cycle-2. Every dispatched command and every processed day/
// arrival/tick along the way is already captured by CampaignRunner's own
// `trace`/`hashLog` (sim/trace.ts) — this module only assembles the two
// phases around the reload point, so e2e/parity.spec.ts's browser walk and
// the headless expectations it compares against are generated by the exact
// same calls, never two hand-copied scripts.
//
// Playwright's own Node test loader cannot import this module's transitive
// graph directly — GameState.ts's `import regionsData from
// '../data/regions.json'` needs an import attribute Playwright's loader
// does not supply (measured: "Module ... needs an import attribute of
// 'type: json'"), unlike Vite's dev/build pipeline and vitest's own loader,
// both of which resolve it fine. sim/parityFixtures.generate.test.ts (a
// vitest test, part of `npx vitest run` — already first in every gate
// sequence this project runs) is therefore the honest generator: it calls
// this module and writes the result to e2e/fixtures/*.json, which
// e2e/parity.spec.ts reads with a plain fs.readFileSync — no import graph,
// no JSON-import-attribute mismatch, and the fixture is regenerated by the
// SAME commit's gate run every time, never hand-edited.

import { createCampaignRunner, type CampaignRunner } from './runner'
import { walkOpeningBriefing, walkQ1Debrief, settleFullAvailable, SECOND_DEADLINE_DAY } from './reserveLine'
import { FIRST_DEADLINE_DAY } from '../quota/quota'
import { world } from '../GameState'
import { parityHash } from '../state/parityView'
import type { CommandTrace, HashStep } from './trace'

export interface ParityFixture {
  seed: number
  /** parityHash at campaign creation, before any command — the browser
   * driver's own fail-fast smoke check before walking the rest. */
  entryParityHash: string
  /** Every command/day/arrival/tick step from creation through the cycle-1
   * pending-settlement decision (NOT yet settled) — replayed before the
   * reload checkpoint. */
  phaseA: HashStep[]
  /** parityHash at the reload checkpoint — asserted equal both immediately
   * before AND after the reload on both runtimes. */
  preReloadParityHash: string
  /** Every step from settling cycle 1 through settling cycle 2. */
  phaseB: HashStep[]
  /** Every command dispatched across the whole line, phase A and B
   * together — phaseA/phaseB 'command' steps index into this ONE array via
   * their own `ref`, matching CampaignRunner.trace's own indexing. */
  trace: CommandTrace
}

/**
 * `walkPhaseA` receives the runner right after Beats 1-2 (briefing/ledger)
 * — reserveLine's `walkToFirstCrew`, or investLine's `walkToFirstCrew` then
 * `walkToSecondCrew`, is what a caller passes.
 */
export function generateParityFixture(seed: number, walkPhaseA: (rc: CampaignRunner) => void): ParityFixture {
  const rc = createCampaignRunner(seed, 'normal')
  const entryParityHash = parityHash(world)

  walkOpeningBriefing(rc)
  walkPhaseA(rc)
  rc.advanceToDay(FIRST_DEADLINE_DAY)

  const phaseA = [...rc.hashLog]
  const preReloadParityHash = parityHash(world)

  // The headless half of the reload checkpoint (07's own protocol item 4).
  const saved = rc.save()
  rc.reload(saved)
  const boundary = rc.hashLog.length

  settleFullAvailable(rc)
  walkQ1Debrief(rc)
  rc.advanceToDay(SECOND_DEADLINE_DAY)
  settleFullAvailable(rc)

  const phaseB = rc.hashLog.slice(boundary)

  return { seed, entryParityHash, phaseA, preReloadParityHash, phaseB, trace: rc.trace }
}
